services:
    mgd_basic.locale_listener:
        class: MGD\BasicBundle\Listener\LocaleListener
        arguments: [%locale%]
        tags:
            -  { name: kernel.event_listener, event: kernel.response, method: onKernelRequest }

    pedido.pago_service:
        class: MGD\BasicBundle\Service\PedidoPagoService
        arguments: [@service_container]

    pedido.finalizarPago:
        class: MGD\BasicBundle\Listener\FinalizarPagoListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: mgd.pedido_pagado, method: onPayment}

    cupon_descuento.controller:
        class:     MGD\BasicBundle\Controller\CuponDescuentoController
        arguments: [@service_container]

    entity.paypal_account.listener:
        class: MGD\BasicBundle\Listener\Entity\PaypalAccountEntityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    entity.paypal_accounts_payments.listener:
        class: MGD\BasicBundle\Listener\Entity\PaypalAccountsPaymentEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist}

    entity.pedido.listener:
        class: MGD\BasicBundle\Listener\Entity\PedidoEntityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


