<?php

namespace Proxies\__CG__\MGD\BasicBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Articulo extends \MGD\BasicBundle\Entity\Articulo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function validateFile(\Symfony\Component\Validator\ExecutionContext $context)
    {
        $this->__load();
        return parent::validateFile($context);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function storeFilenameForRemove()
    {
        $this->__load();
        return parent::storeFilenameForRemove();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setPaypalHtml($paypalHtml)
    {
        $this->__load();
        return parent::setPaypalHtml($paypalHtml);
    }

    public function getPaypalHtml()
    {
        $this->__load();
        return parent::getPaypalHtml();
    }

    public function setPrecio($precio)
    {
        $this->__load();
        return parent::setPrecio($precio);
    }

    public function getPrecio()
    {
        $this->__load();
        return parent::getPrecio();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setImagenPath($imagenPath)
    {
        $this->__load();
        return parent::setImagenPath($imagenPath);
    }

    public function getImagenPath()
    {
        $this->__load();
        return parent::getImagenPath();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'precio', 'imagenPath', 'paypalHtml');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}