imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'MGDBasicBundle','MGDAdminBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
                    file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
                    apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

gregwar_captcha: ~

orderly_pay_pal_ipn:

        # If set to false then service loads settings with "sandbox_" prefix
        islive:  %paypal_is_live%

        # Constants for the live environment (default settings in Configuration.php)
        email:   %paypal_email%
        url:     https://www.paypal.com/cgi-bin/webscr
        debug:   %kernel.debug%

        # Constants for the sandbox environment (default settings in Configuration.php)
        sandbox_email:   %paypal_email_sandbox%
        sandbox_url:     https://www.sandbox.paypal.com/cgi-bin/webscr
        sandbox_debug:   true

        drivers:
            orm:
                object_manager: doctrine.orm.entity_manager
                classes: ~

