imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

bazinga_faker:
    locale: gb_GB
    orm: doctrine
    entities:
        MGD\BasicBundle\Entity\Articulo:
            number: 3
            custom_formatters:
                nombre: { method: randomElement, parameters: [['50 Referrals','250 Referrals','300 Referrals']] }
                precio: { method: randomNumber, parameters: [50,400] }
                paypalHtml: { method: sentence }
        MGD\FrameworkBundle\Entity\Usuario:
            number: 1
        MGD\BasicBundle\Entity\Estado:
            number: 1
            custom_formatters:
                nombre: { method: word }
        MGD\BasicBundle\Entity\Pedido:
            number: 20
            custom_formatters:
                id: { method: uuid }
                referralLink: { method: uuid }
                ip: { method: ipv4 }
        MGD\BasicBundle\Entity\PedidoEstados:
            number: 40
        MGD\BasicBundle\Entity\Noticia:
            number: 30
            custom_formatters:
                titulo: { method: sentence }
                noticia: { method: text }

        MGD\BasicBundle\Entity\CuponDescuento:
            number: 30
            custom_formatters:
                id: { method: uuid }




#swiftmailer:
#    delivery_address: me@example.com
