imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug



assetic:
    use_controller: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

bazinga_faker:
    locale: gb_GB
    orm: doctrine
    entities:

# Bundle crashed text() can only generate text of at least 5 characters

        MGD\FrameworkBundle\Entity\Usuario:
            number: 1

#        MGD\BasicBundle\Entity\Estado:
#            number: 1
#            custom_formatters:
#                nombre: { method: word, unique: true }
#
#        MGD\BasicBundle\Entity\Pedido:
#            number: 20
#            custom_formatters:
#                id: { method: uuid }
#                referralLink: { method: uuid }
#                ip: { method: ipv4 }
#
#        MGD\BasicBundle\Entity\PedidoEstados:
#            number: 40
#
#        MGD\BasicBundle\Entity\PedidoBots:
#            number: 40
#            custom_formatters:
#                nombre: { method: uuid }
#                contrasena: { method: word }
#                lvl: { method: randomNumber, parameters: [0,10] }
#
#        MGD\BasicBundle\Entity\Noticia:
#            number: 30
#            custom_formatters:
#                titulo: { method: sentence }
#                noticia: { method: text }
#
#        MGD\BasicBundle\Entity\CuponDescuento:
#            number: 30
#            custom_formatters:
#                id: { method: uuid }
#
#        MGD\BasicBundle\Entity\PaypalAccount:
#            number: 6
#            custom_formatters:
#                name: { method: word, unique: true }
#                apiUsername: { method: email, unique: true }
#                apiPassword: { method: word }
#                apiSignature: { method: word }
#
#
#        MGD\BasicBundle\Entity\PaypalAccountsPayment:
#            number: 10



#swiftmailer:
#    delivery_address: me@example.com
