mgd_admin:
    resource: "@MGDAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

mgd_basic:
    resource: "@MGDBasicBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    path:  /
    defaults: { _controller: MGDBasicBundle:Default:index, _locale: es  }

OrderlyPayPalIpnBundleEmail:
    resource: "@OrderlyPayPalIpnBundle/Controller/"
    type:     annotation
    prefix:   /ipn/
