jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        MGD\FrameworkBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_LECTOR, ROLE_EDITOR]
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN]

    providers:
        user_db:
            entity: { class: MGD\FrameworkBundle\Entity\Usuario, property: username }
        in_memory:
            memory:
                users:
                    protected:  { password: %protected_password%, roles: 'ROLE_PROTECTED' }

    firewalls:
        protected:
            provider: in_memory
            pattern:   ^/protected
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
        main:
            pattern: /.*
            provider: user_db
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
                #remember_me: true
            logout:
                path: /admin/logout
                target: /
            remember_me:
                key: %secret%
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true


    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/estadisticas, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/usuario, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/rol, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/articulo, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/estado, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/paypalaccount, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin/paypalaccountspayments, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin, roles: [ROLE_LECTOR,ROLE_EDITOR,ROLE_ADMIN,ROLE_SUPER_ADMIN]}
        - { path: ^/protected, roles: [ROLE_PROTECTED]}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
