<?php

namespace MGD\BasicBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PedidoBots
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoBotsRepository extends EntityRepository
{
    public function isCompletedByPedido(Pedido $pedido)
    {
        $result = $this->getEntityManager()
            ->createQuery('
            SELECT count(p.nombre)
            FROM MGDBasicBundle:PedidoBots p
            WHERE
                p.lvl < :lvl
                AND p.pedido = :pedido

            ')
            ->setParameters(array('lvl' => 10, 'pedido' => $pedido))
            ->getSingleScalarResult();

        return $result> 0 ? false: true;
    }

    public function isFirstLvlByPedido(Pedido $pedido)
    {
        $result = $this->getEntityManager()
            ->createQuery('
            SELECT count(p.nombre)
            FROM MGDBasicBundle:PedidoBots p
            WHERE
                p.lvl > :lvl
                AND p.pedido = :pedido

            ')
            ->setParameters(array('lvl' => 0, 'pedido' => $pedido))
            ->getSingleScalarResult();

        return $result == 1 ? true : false;
    }
}
