<?php

namespace MGD\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PedidoController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/xampp/htdocs/lol/app/cache/dev/jms_diextra/proxies/MGD-AdminBundle-Controller-PedidoController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('MGD\\AdminBundle\\Controller\\PedidoController' => array('createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_e40c0edfc31609ee5c97b6c2cc72220b7e05a4f6\__CG__\MGD\AdminBundle\Controller\PedidoController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
