<?php

namespace MGD\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContactoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MGD\AdminBundle\Controller\ContactoController();
        return $instance;
    }
}
