<?php

namespace MGD\BasicBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LanguageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MGD\BasicBundle\Controller\LanguageController();
        return $instance;
    }
}
