<?php

namespace Orderly\PayPalIpnBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TwigNotificationEmailController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orderly\PayPalIpnBundle\Controller\TwigNotificationEmailController();
        return $instance;
    }
}
